simloto7:
  ros2__parameters:
    num_of_trials: 10000
    price: 300
    total_num: 10295472
    num_of_first_prize: 1
    num_of_second_prize: 14
    num_of_third_prize: 196
    num_of_fourth_prize: 9135
    num_of_fifth_prize: 142100
    num_of_sixth_prize: 242550
    num_of_seventh_prize: 0
    num_of_eighth_prize: 0
    num_of_ninth_prize: 0
    prize_of_first_prize: 600000000
    prize_of_second_prize: 7300000
    prize_of_third_prize: 730000
    prize_of_fourth_prize: 9100
    prize_of_fifth_prize: 1400
    prize_of_sixth_prize: 1000
    prize_of_seventh_prize: 0
    prize_of_eighth_prize: 0
    prize_of_ninth_prize: 0

