name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: build and test
        run: |
          rsync -av ./ /root/ros2_ws/src/simloto7/
          pip install numpy
          cd /root/ros2_ws
          bash -xv ./src/simloto7/test/test.bash /root
